### ISSUE TITLE
cakePhp upgrate to 4.0 -  bin/cake upgrade rector --rules phpunit80

### ISSUE THREAD

**Issue by codelatest** [cakephp/upgrade#222] opened 2023-03-10 12:50 UTC
### Description

When hitting the command - 
 bin/cake upgrade rector --rules phpunit80  /opt/lampp/htdocs/newagent/cakefull/tests/ -v
**Get issue -**
   **The "--set" option does not exist.**  

This above message showing - 

**Please see the full command -** 

**Command -**
 bin/cake upgrade rector --rules phpunit80 /opt/lampp/htdocs/newagent/cakefull/tests/ -v
 
**Result**
gurinder@gurinder-Inspiron-3593:/opt/lampp/htdocs/upgrade$ ^C
gurinder@gurinder-Inspiron-3593:/opt/lampp/htdocs/upgrade$ ^C
gurinder@gurinder-Inspiron-3593:/opt/lampp/htdocs/upgrade$ bin/cake upgrade rector --rules phpunit80 /opt/lampp/htdocs/newagent/cakefull/tests/ -v
Detecting autoload file for /opt/lampp/htdocs/newagent/cakefull/tests
-> Checking /opt/lampp/htdocs/newagent/cakefull/tests/vendor/autoload.php
-> Checking /opt/lampp/htdocs/newagent/cakefull/vendor/autoload.php
-> Found /opt/lampp/htdocs/newagent/cakefull/vendor/autoload.php
Running /opt/lampp/htdocs/upgrade/vendor/bin/rector process  --autoload-file='/opt/lampp/htdocs/newagent/cakefull/vendor/autoload.php' --set='phpunit80' --working-dir='/opt/lampp/htdocs/newagent/cakefull/tests' '/opt/lampp/htdocs/newagent/cakefull/tests'

                                      
  The "--set" option does not exist.  
                                      

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--output-format OUTPUT-FORMAT] [--debug] [--memory-limit MEMORY-LIMIT] [--clear-cache] [--port PORT] [--identifier IDENTIFIER] [--] [<source>...]

### CakePHP Version

3.9

### PHP Version

7.4

**Comment by LordSimal** [comment] 2023-03-10 13:10
What version of cakephp/upgrade are you using?

**Comment by codelatest** [comment] 2023-03-10 13:22
> What version of cakephp/upgrade are you using?

cakePhp current code version is  - 3.9
cakephp/upgrade version is -  4.0

Please check the image -

![image](https://user-images.githubusercontent.com/127506051/224330164-e1682daf-493f-4df1-b444-7263f6fd9084.png)

**Comment by LordSimal** [comment] 2023-03-10 13:56
I am unable to reproduce your problem with a fresh cakephp 3.9 app and the current 4.x version of cakephp/upgrade

How did you "install" the upgrade tool?

```
kevinpfeifer@Kevins-MBP [14:54:18] [~/Desktop/tmp/tmp-setup/upgrade] 
-> % bin/cake upgrade file_rename locales ../app 
Renaming /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/src/Locale

kevinpfeifer@Kevins-MBP [14:54:24] [~/Desktop/tmp/tmp-setup/upgrade] 
-> % bin/cake upgrade file_rename templates ../app
Renaming /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/src/Template
Moving sub directories of /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/templates
Recursively changing extensions in /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/templates

kevinpfeifer@Kevins-MBP [14:54:30] [~/Desktop/tmp/tmp-setup/upgrade] 
-> % bin/cake upgrade rector --rules phpunit80 ../app/tests -v
Detecting autoload file for /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/tests
-> Checking /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/tests/vendor/autoload.php
-> Checking /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php
-> Found /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php
Running /Users/kevinpfeifer/Desktop/tmp/tmp-setup/upgrade/vendor/bin/rector process  --autoload-file='/Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php' --config='/Users/kevinpfeifer/Desktop/tmp/tmp-setup/upgrade/config/rector/phpunit80.php' '/Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/tests' --clear-cache



 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [OK] Rector is done!                                                           



Rector applied successfully

kevinpfeifer@Kevins-MBP [14:54:59] [~/Desktop/tmp/tmp-setup/upgrade] 
-> % bin/cake upgrade rector --rules cakephp40 ../app/src -v  
Detecting autoload file for /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/src
-> Checking /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/src/vendor/autoload.php
-> Checking /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php
-> Found /Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php
Running /Users/kevinpfeifer/Desktop/tmp/tmp-setup/upgrade/vendor/bin/rector process  --autoload-file='/Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/vendor/autoload.php' --config='/Users/kevinpfeifer/Desktop/tmp/tmp-setup/upgrade/config/rector/cakephp40.php' '/Users/kevinpfeifer/Desktop/tmp/tmp-setup/app/src' --clear-cache


 8/8 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
3 files with changes
====================

1) ../app/src/Controller/ErrorController.php:27


    ---------- begin diff ----------
@@ @@
      *
      * @return void
      */
-    public function initialize()
+    public function initialize(): void
     {
         $this->loadComponent('RequestHandler', [
             'enableBeforeRedirect' => false,
@@ @@
      * @param \Cake\Event\Event $event Event.
      * @return \Cake\Http\Response|null|void
      */
-    public function beforeFilter(Event $event)
+    public function beforeFilter(\Cake\Event\EventInterface $event)
     {
     }

@@ @@
      * @param \Cake\Event\Event $event Event.
      * @return \Cake\Http\Response|null|void
      */
-    public function beforeRender(Event $event)
+    public function beforeRender(\Cake\Event\EventInterface $event)
     {
         parent::beforeRender($event);

@@ @@
      * @param \Cake\Event\Event $event Event.
      * @return \Cake\Http\Response|null|void
      */
-    public function afterFilter(Event $event)
+    public function afterFilter(\Cake\Event\EventInterface $event)
     {
     }
 }
    ----------
- end diff -----------

Applied rules:
 * RenamePropertyRector
 * AddParamTypeDeclarationRector
 * AddReturnTypeDeclarationRector


2) ../app/src/Controller/AppController.php:36

    ---------- begin diff ----------
@@ @@
      *
      * @return void
      */
-    public function initialize()
+    public function initialize(): void
     {
         parent::initialize();
    ----------- end diff -----------

Applied rules:
 * RenamePropertyRector
 * AddReturnTypeDeclarationRector


3) ../app/src/Application.php:31

    ---------- begin diff ----------
@@ @@
     /**
      * {@inheritDoc}
      */
-    public function bootstrap()
+    public function bootstrap(): void
     {
         // Call parent to load bootstrap from files.
         parent::bootstrap();
@@ @@
      * @param \Cake\Http\MiddlewareQueue $middlewareQueue The middleware queue to setup.
      * @return \Cake\Http\MiddlewareQueue The updated middleware queue.
      */
-    public function middleware($middlewareQueue)
+    public function middleware
($middlewareQueue): \Cake\Http\MiddlewareQueue
     {
         $middlewareQueue
             // Catch any exceptions in the lower layers,
@@ @@
     /**
      * @return void
      */
-    protected function bootstrapCli()
+    protected function bootstrapCli(): void
     {
         try {
             $this->addPlugin('Bake');
    ----------- end diff -----------

Applied rules:
 * RenamePropertyRector
 * AddReturnTypeDeclarationRector


 [OK] 3 files have been changed by Rector                                                       


Rector applied successfully
```

**Comment by codelatest** [comment] 2023-03-10 14:00
Yes I install upgrade tools and can you please tell me of your php version ? I am using 7.4

**Comment by LordSimal** [comment] 2023-03-10 14:02
CakePHP 3 can at most be run with PHP 7.4 because it doesn't support PHP 8.0+

But the upgrade tool is its own, separate application which should be run independently from CakePHP.

The current 4.x branch requires PHP 8.0+ so PHP 8.0 is what I used.

**Comment by codelatest** [comment] 2023-03-10 14:03
Ok thanks I will upgrade to php 8 then try . After I let you know 
Thanks

**Comment by LordSimal** [comment] 2023-03-10 14:05
Otherwise I would just recommend you jump directly to CakePHP 4.0 and just fix errors, warnings etc. one after the other till your app works again.
The upgrade tool won't catch everything and there will be manual adjustments required anyways so don't spend too much time fiddeling around with it 😉

**Comment by codelatest** [comment] 2023-03-11 07:38
I upgrade PHP 8.0.28 now issue is solved thank's
But when hit this command -
**composer require --dev --update-with-dependencies "phpunit/phpunit:^8.0"**
I got a problem -
```
  Problem 1
    - cakephp/cakephp[3.10.0, ..., 3.10.5] require php >=5.6.0,<8.0.0 -> your php version (8.0.28) does not satisfy that requirement.
    - Root composer.json requires cakephp/cakephp 3.10.* -> satisfiable by cakephp/cakephp[3.10.0, ..., 3.10.5].
```

And after this -

**composer  require --update-with-dependencies "cakephp/cakephp:4.0.*" --ignore-platform-reqs**

```
  Problem 1
    - Root composer.json requires cakephp/cakephp 4.0.*, found cakephp/cakephp[4.0.0, ..., 4.0.10] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - cakephp/bake is locked to version 1.12.0 and an update of this package was not requested.
    - cakephp/bake 1.12.0 requires cakephp/cakephp ^3.8.0 -> found cakephp/cakephp[3.8.0, ..., 3.10.5] but it conflicts with your root composer.json require (4.0.*).
  Problem 3
    - cakephp/debug_kit is locked to version 3.23.0 and an update of this package was not requested.
    - cakephp/debug_kit 3.23.0 requires cakephp/cakephp ^3.7.0 -> found cakephp/cakephp[3.7.0, ..., 3.10.5] but it conflicts with your root composer.json require (4.0.*).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

And my composer.json file is -
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php":"^8.0.28 || ^8.1",
        "cakephp/cakephp": "3.10.*",
        "cakephp/migrations": "^2.0.0",
        "cakephp/plugin-installer": "^1.3",
        "mobiledetect/mobiledetectlib": "2.*"
    },
    "require-dev": {
        "cakephp/bake": "^1.9.0",
        "cakephp/cakephp-codesniffer": "^3.0",
        "cakephp/debug_kit": "^3.17.0",
        "josegonzalez/dotenv": "3.*",
        "phpunit/phpunit": "^8.0.28",
        "psy/psysh": "@stable"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan/Psalm compatibility."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests/",
            "Cake\\Test\\": "vendor/cakephp/cakephp/tests/"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/ config/ webroot/",
        "cs-fix": "phpcbf --colors -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/ config/ webroot/",
        "stan": "phpstan analyse -l 5 src/",
        "stan-setup": "cp composer.json composer.backup && composer require --dev phpstan/phpstan-shim:^0.11 && mv composer.backup composer.json",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "cakephp/plugin-installer": true
        }
    }
}
```

**Comment by LordSimal** [comment] 2023-03-11 08:01
If you pin your composer.json to be PHP 8.0+ then you have to adjust your other dependencies to be PHP 8.0 compatible as well.
so the description in https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html won't work anymore because it expects you still allow PHP 7.2+

Adjust your composer.json to have
```
"require": {
    "php": ">=7.2|>=8.0",
    "cakephp/cakephp": "4.0.*",
    "cakephp/migrations": "^3.0",
    "cakephp/plugin-installer": "^1.3",
    "mobiledetect/mobiledetectlib": "^3.74"
},
```

and then run `composer update -W`

**Comment by codelatest** [comment] 2023-03-11 08:13
After changing composer.json run this comand
**composer  require --dev --update-with-dependencies "phpunit/phpunit:^8.0"**

 Problem 1
    - Root composer.json requires cakephp/cakephp-codesniffer ~4.1.0 -> satisfiable by cakephp/cakephp-codesniffer[4.1.0, 4.1.1].
    - cakephp/cakephp-codesniffer[4.1.0, ..., 4.1.1] require php ^7.2 -> your php version (8.0.28) does not satisfy that requirement.

**Comment by LordSimal** [comment] 2023-03-11 08:18
Right, you need the `require-dev` part as well. Missed that one... Try
```
    "require": {
        "php": ">=7.2|>=8.0",
        "cakephp/cakephp": "4.0.*",
        "cakephp/migrations": "^3.0",
        "cakephp/plugin-installer": "^1.3",
        "mobiledetect/mobiledetectlib": "^3.74"
    },
    "require-dev": {
        "cakephp/bake": "^2.0",
        "cakephp/cakephp-codesniffer": "^4.0",
        "cakephp/debug_kit": "^4.0",
        "josegonzalez/dotenv": "^3.0",
        "phpunit/phpunit": "~8.5 || ^9.3"
    },
```
Then you don't need those `composer require` commands. Just `composer update -W`. Then check your app and fix the rest of the warnings/errors

**Comment by codelatest** [comment] 2023-03-11 08:29
**bin/cake server** command now giving errors -
PHP Deprecated:  Use Cake\Error\ConsoleErrorHandler instead of Cake\Console\ConsoleErrorHandler. - /var/www/html/my_app_name/vendor/composer/ClassLoader.php, line: 571
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in /var/www/html/my_app_name/vendor/cakephp/cakephp/src/Core/functions.php on line 305

Deprecated: Use Cake\Error\ConsoleErrorHandler instead of Cake\Console\ConsoleErrorHandler. - /var/www/html/my_app_name/vendor/composer/ClassLoader.php, line: 571
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in /var/www/html/my_app_name/vendor/cakephp/cakephp/src/Core/functions.php on line 305
PHP Fatal error:  Declaration of App\Shell\ConsoleShell::getOptionParser() must be compatible with Cake\Console\Shell::getOptionParser(): Cake\Console\ConsoleOptionParser in /var/www/html/my_app_name/src/Shell/ConsoleShell.php on line 67

Fatal error: Declaration of App\Shell\ConsoleShell::getOptionParser() must be compatible with Cake\Console\Shell::getOptionParser(): Cake\Console\ConsoleOptionParser in /var/www/html/my_app_name/src/Shell/ConsoleShell.php on line 67

**Comment by LordSimal** [comment] 2023-03-11 08:36
[Shell is deprecated.](https://book.cakephp.org/3/en/console-and-shells/shells.html) If you don't need your `src/Shell/ConsoleShell.php` then just remove it.
Otherwise you need to follow what is said in the error and adjust your `ConsoleShell::getOptionParser()` to be compatible (aka identical arguments and return type) as its parent class method `Cake\Console\Shell::getOptionParser()`
See https://github.com/cakephp/cakephp/blob/4.0.10/src/Console/Shell.php#L573-L588

Everything onward now doesn't concern the upgrade tool anymore since its the normal CakePHP upgrade process. Therefore I will close this issue.
If you need further help with your upgrade please join our slack/discord server or ask questions in our discourse forum.
https://cakephp.org/get-involved#getHelp

**Closed as completed by LordSimal** 2023-03-11 08:36 UTC
Labels: support
