### ISSUE TITLE
Call to undefined method Cake\Upgrade\Application::pluginEvents()

### ISSUE THREAD

**Issue by alexvanniel** [cakephp/upgrade#299] opened 2024-09-24 12:30 UTC
I have followed the upgrade guide to the letter as far as I am aware of.
However, when I run the upgrade tool on my CakePHP 4.5.7 src/ I get the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Cake\Upgrade\Application::pluginEvents() in /mnt/projects/cakephp-upgrade/upgrade/vendor/cakephp/console/CommandRunner.php:323
Stack trace:
#0 /mnt/projects/cakephp-upgrade/upgrade/vendor/cakephp/console/CommandRunner.php(167): Cake\Console\CommandRunner->runCommand()
#1 /mnt/projects/cakephp-upgrade/upgrade/bin/cake.php(12): Cake\Console\CommandRunner->run()
#2 {main}
  thrown in /mnt/projects/cakephp-upgrade/upgrade/vendor/cakephp/console/CommandRunner.php on line 323
```

I have done:
```git checkout 5.x```
```composer install --no-dev```
But I keep getting this error. 

Am I doing something wrong? Is this a bug? Can someone please advise?

To clarify, I did NOT install the upgrade tool inside my CakePHP 4.5 project, I installed it OUTSIDE of the project in a separate folder away from the project that needs to be upgraded.

**Comment by ADmad** [comment] 2024-09-24 12:43
Duplicate of  https://github.com/cakephp/cakephp/issues/17923

**Closed as completed by ADmad** 2024-09-24 12:43 UTC
