### ISSUE TITLE
Deprecated: PHP configuration files like "app.php" should not set `$config`.

### ISSUE THREAD

**Issue by jsonjuri** [cakephp/upgrade#119] opened 2019-02-28 06:37 UTC
Clean install with CakePHP: 3.7.4
Installed this upgrade tool: https://github.com/cakephp/upgrade

$ cd upgrade
$ bin/cake upgrade --help

Deprecated: PHP configuration files like "app.php" should not set `$config`. Instead return an array. - D:\my_app\upgrade\vendor\cakephp\cakephp\src\Core\Configure.php, line: 343 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in D:\my_app\upgrade\vendor\cakephp\cakephp\src\Core\functions.php on line 311
Exception: If config is null, key must be an array. in [D:\my_app\upgrade\vendor\cakephp\cakephp\src\Core\StaticConfigTrait.php, line 79]

"You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php." does not have any effect.

When change $config = [] to return [] in upgrade/config/app.php
$ bin/cake upgrade --help
Exception: If config is null, key must be an array. in [D:\my_app\upgrade\vendor\cakephp\cakephp\src\Core\StaticConfigTrait.php, line 79]

**Comment by garas** [comment] 2019-02-28 09:52
Duplicate of https://github.com/cakephp/upgrade/issues/98

Look at https://github.com/cakephp/upgrade/issues/98#issuecomment-467529990 and other comments for possible workarounds.

**Closed by garas** 2019-02-28 09:52 UTC
